{
 "title": "Host Dashboard",
 "tags": [
  "Linux",
  "InfluxDB"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"Host\""
    }
   },
   {
    "name": "Web_Name",
    "label": "Web_Name",
    "query": {
     "query": "show tag values with key=\"i_Web_Name\""
    }
   },
   {
    "name": "Drive_Name",
    "label": "Drive_Name",
    "query": {
     "query": "show tag values with key = \"i_Drive_Name\""
    }
   },
   {
    "name": "Partition_Name",
    "label": "Partition_Name",
    "query": {
     "query": "show tag values with key = \"i_Partition_Name\""
    }
   },
   {
    "name": "Data_Name",
    "label": "Data_Name",
    "query": {
     "query": "show tag values with key=\"i_Data_Name\""
    }
   }
  ]
 },
 "panels": [
  { "title": "配置信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Host 状态",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host_Status",
     "query": "SELECT last(\"memory_max\") - last(\"memory_used\") FROM \"memory_usage\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Host_Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "响应时间",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host_Status",
     "query": "SELECT last(\"memory_max\") - last(\"memory_used\") FROM \"memory_usage\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "m_Response_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "操作系统版本",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "select": [
      [
       { "params": [ "j_OS_Version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "内核版本",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "select": [
      [
       { "params": [ "k_Kernel_Version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "上传流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Traffic_Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "j_Traffic_Type::tag", "operator": "=", "value": "Bytes_sent" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "下载流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Traffic_Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "j_Traffic_Type::tag", "operator": "=", "value": "Bytes_recv" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU使用率",
     "measurement": "Cpu_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "j_Cpu_Percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 1",
     "measurement": "Cpu_Load",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "j_Load_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 5",
     "measurement": "Cpu_Load",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Load_5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 15",
     "measurement": "Cpu_Load",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l_Load_15" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "启动时间",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "select": [
      [
       { "params": [ "l_Uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU核心数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_Cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "/ 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "/home 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/home" }
     ]
    },
    {
     "alias": "/Audit 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/Audit" }
     ]
    },
    {
     "alias": "/data 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/data" }
     ]
    },
    {
     "alias": "/db_log 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/db_log" }
     ]
    },
    {
     "alias": "/db_data 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/db_data" }
     ]
    },
    {
     "alias": "/mysql 分区总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "/mysql" }
     ]
    },
    {
     "alias": "C盘总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "C" }
     ]
    },
    {
     "alias": "D盘总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "D" }
     ]
    },
    {
     "alias": "E盘总容量",
     "groupBy": [
      { "params": [ "partition_name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "k_Disk_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=", "value": "E" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "已用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "k_Memory_Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "可用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "l_Memory_Available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "总进程数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "o_Processes_Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "总内存",
     "measurement": "Memory_Usage",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "j_Memory_Max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "负载信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU总览",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cpu_Usage",
     "select": [
      [
       { "params": [ "j_Cpu_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cpu_Load",
     "select": [
      [
       { "params": [ "j_Load_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cpu_Load",
     "select": [
      [
       { "params": [ "k_Load_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Load 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cpu_Load",
     "select": [
      [
       { "params": [ "l_Load_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "alias": "下载",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface_Usage",
     "select": [
      [
       { "params": [ "k_Traffic_Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "j_Traffic_Type::tag", "operator": "=", "value": "Bytes_recv" }
     ]
    },
    {
     "alias": "上传",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface_Usage",
     "select": [
      [
       { "params": [ "k_Traffic_Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "j_Traffic_Type::tag", "operator": "=", "value": "Bytes_sent" }
     ]
    }
   ]
  },
  {
   "title": "内存总览",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "已用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "k_Memory_Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "可用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "l_Memory_Available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "最大内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "j_Memory_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Used %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Memory_Usage",
     "select": [
      [
       { "params": [ "n_Memory_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "总进程数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "System_Info",
     "select": [
      [
       { "params": [ "o_Processes_Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "磁盘信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "磁盘分区列表",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "i_Partition_Name::tag" ], "type": "tag" }
     ],
     "measurement": "Disk_Usage",
     "select": [
      [
       { "params": [ "o_Disk_Percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "磁盘读写",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "alias": "$Drive_Name Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Disk_IO",
     "select": [
      [
       { "params": [ "l_IO_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Drive_Name::tag", "operator": "=~", "value": "/^$Drive_Name$/" },
      { "condition": "AND", "key": "k_IO_Type::tag", "operator": "=", "value": "Read_bytes" }
     ]
    },
    {
     "alias": "$Drive_Name Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Disk_IO",
     "select": [
      [
       { "params": [ "l_IO_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Drive_Name::tag", "operator": "=~", "value": "/^$Drive_Name$/" },
      { "condition": "AND", "key": "k_IO_Type::tag", "operator": "=", "value": "Write_bytes" }
     ]
    }
   ]
  },
  {
   "title": "磁盘空间",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$Partition_Name 分区已使用空间",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Disk_Usage",
     "select": [
      [
       { "params": [ "l_Disk_Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=~", "value": "/^$Partition_Name$/" }
     ]
    },
    {
     "alias": "$Partition_Name 分区空闲空间",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Disk_Usage",
     "select": [
      [
       { "params": [ "m_Disk_Free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=~", "value": "/^$Partition_Name$/" }
     ]
    },
    {
     "alias": "$Partition_Name 分区已用 %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Disk_Usage",
     "query": "SELECT last(\"l_Disk_Used\") / last(\"k_Disk_Max\") * 100 FROM \"Disk_Usage\" WHERE (\"Host\"::tag =~ /^$Host$/ AND \"i_Partition_Name\"::tag =~ /^$Partition_Name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l_Disk_Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Partition_Name::tag", "operator": "=~", "value": "/^$Partition_Name$/" }
     ]
    }
   ]
  },
  { "title": "网站信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "网站列表",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "http_status",
     "query": "SELECT last(\"m_Http_Code\") as \"Http_Code\",last(\"n_Response_Time\") as \"Response_Time\" FROM \"Web_Status\" WHERE (\"Host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"j_Web_Port\"::tag, \"Host\"::tag, \"i_Web_Name\"::tag",
     "select": [
      [
       { "params": [ "http_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "网站状态",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$Web_Name Http Code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Web_Status",
     "select": [
      [
       { "params": [ "m_Http_Code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Web_Name::tag", "operator": "=~", "value": "/^$Web_Name$/" }
     ]
    },
    {
     "alias": "$Web_Name Response Time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Web_Status",
     "select": [
      [
       { "params": [ "n_Response_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Web_Name::tag", "operator": "=~", "value": "/^$Web_Name$/" }
     ]
    }
   ]
  },
  { "title": "数据库信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "数据库版本",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "MySQL_Version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "数据流入",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_received_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "QPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "数据流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "流入",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Bytes_received_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "流出",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Bytes_sent_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "启动时间",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "数据流出",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_sent_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "TPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "连接数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Threads_connected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "慢查询",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Slow_queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "负载信息",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "QPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "TPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "慢查询",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Slow_queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "当前连接数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Threads_connected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "缓存连接数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Threads_cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "InnoDB缓冲池",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "命中率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_reads_hitrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "使用率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_use_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "脏块率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_dirty_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "InnoDB引擎",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "alias": "查询",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_rows_read_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "插入",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_rows_inserted_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "删除",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_rows_deleted_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "更新",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MySQL_Status",
     "select": [
      [
       { "params": [ "Innodb_rows_updated_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "业务数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "数据列表",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "http_status",
     "query": "SELECT last(\"m_Data_Value\") as \"当前数据量\" FROM \"Business_Data\" WHERE (\"Host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"Host\"::tag, \"i_Data_Name\"::tag, \"k_Data_Comment\"::tag",
     "select": [
      [
       { "params": [ "http_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "数据统计",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$Data_Name 最新数据量",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Business_Data",
     "select": [
      [
       { "params": [ "m_Data_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Host::tag", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "i_Data_Name::tag", "operator": "=~", "value": "/^$Data_Name$/" }
     ]
    }
   ]
  }
 ]
}